server:
  port: 8080

spring:
  application:
    name: "playqd-media-server"
  cache:
    jcache:
      provider: "org.ehcache.jsr107.EhcacheCachingProvider"

  datasource:
    url: "jdbc:mysql://localhost:8306/db_name"
    username: "root"
    password: "****"
  freemarker:
    enabled: true
    suffix: ".ftl"
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        format_sql: false
        show_sql: false
        enable_lazy_load_no_trans: true
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    enabled: false

playqd:
  mediaSources:
    local:
      name: "All music"
      dir: "path_to_folder"
      scanOnStart: true
      ignoreDirs: [ ]
  logging:
    logSoapResponse: false
  workingDir: "${user.home}/.playqd"
  upnp:
    action:
      browse:
        maxDisplayedRecentlyAdded: 100
        maxDisplayedRecentlyPlayed: 100
    streamServer:
      host: "192.168.1.122"
      port: ${server.port}

management:
  endpoint:
    caches:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ "info", "health", "caches", "metrics", "prometheus", "shutdown" ]


logging:
  level:
    org.jaudiotagger.audio: ERROR
    org.jaudiotagger.tag: ERROR

    org.jupnp: WARN
    org.jupnp.transport: WARN

    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.data: INFO
    org.springframework.web: INFO
    org.springframework.ws: INFO

    io.playqd: INFO
    io.playqd.mediaserver.api.soap.interceptor.PrettyPrintPayloadLoggingInterceptor: INFO
